# Generated by Django 4.2.9 on 2025-05-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_alter_applicant_id_alter_bookmarkjob_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('MKT', 'Marketing'), ('HR', 'Human Resources')], max_length=50),
        ),
    ]
